// ISO 3166-1 alpha-2 codes para todos os times da Copa 2026
const TEAM_CODES: Record<string, string> = {
  Algeria: 'dz',
  Argentina: 'ar',
  Australia: 'au',
  Austria: 'at',
  Belgium: 'be',
  'Bosnia and Herzegovina': 'ba',
  Brazil: 'br',
  Canada: 'ca',
  'Cape Verde': 'cv',
  Colombia: 'co',
  Croatia: 'hr',
  'Curaçao': 'cw',
  'Czech Republic': 'cz',
  'Democratic Republic of the Congo': 'cd',
  Ecuador: 'ec',
  Egypt: 'eg',
  England: 'gb-eng',
  France: 'fr',
  Germany: 'de',
  Ghana: 'gh',
  Haiti: 'ht',
  Iran: 'ir',
  Iraq: 'iq',
  'Ivory Coast': 'ci',
  Japan: 'jp',
  Jordan: 'jo',
  Mexico: 'mx',
  Morocco: 'ma',
  Netherlands: 'nl',
  'New Zealand': 'nz',
  Norway: 'no',
  Panama: 'pa',
  Paraguay: 'py',
  Portugal: 'pt',
  Qatar: 'qa',
  'Saudi Arabia': 'sa',
  Scotland: 'gb-sct',
  Senegal: 'sn',
  'South Africa': 'za',
  'South Korea': 'kr',
  Spain: 'es',
  Sweden: 'se',
  Switzerland: 'ch',
  Tunisia: 'tn',
  Turkey: 'tr',
  'United States': 'us',
  Uruguay: 'uy',
  Uzbekistan: 'uz',
}

export function getFlagUrl(teamName: string): string {
  const code = TEAM_CODES[teamName]
  if (!code) return ''
  return `/flags/${code}.png`
}

const TEAM_NAMES_PT: Record<string, string> = {
  Algeria: 'Argélia',
  Argentina: 'Argentina',
  Australia: 'Austrália',
  Austria: 'Áustria',
  Belgium: 'Bélgica',
  'Bosnia and Herzegovina': 'Bósnia e Herz.',
  Brazil: 'Brasil',
  Canada: 'Canadá',
  'Cape Verde': 'Cabo Verde',
  Colombia: 'Colômbia',
  Croatia: 'Croácia',
  'Curaçao': 'Curaçao',
  'Czech Republic': 'Rep. Tcheca',
  'Democratic Republic of the Congo': 'Rep. D. Congo',
  Ecuador: 'Equador',
  Egypt: 'Egito',
  England: 'Inglaterra',
  France: 'França',
  Germany: 'Alemanha',
  Ghana: 'Gana',
  Haiti: 'Haiti',
  Iran: 'Irã',
  Iraq: 'Iraque',
  'Ivory Coast': 'Costa do Marfim',
  Japan: 'Japão',
  Jordan: 'Jordânia',
  Mexico: 'México',
  Morocco: 'Marrocos',
  Netherlands: 'Holanda',
  'New Zealand': 'Nova Zelândia',
  Norway: 'Noruega',
  Panama: 'Panamá',
  Paraguay: 'Paraguai',
  Portugal: 'Portugal',
  Qatar: 'Catar',
  'Saudi Arabia': 'Arábia Saudita',
  Scotland: 'Escócia',
  Senegal: 'Senegal',
  'South Africa': 'África do Sul',
  'South Korea': 'Coreia do Sul',
  Spain: 'Espanha',
  Sweden: 'Suécia',
  Switzerland: 'Suíça',
  Tunisia: 'Tunísia',
  Turkey: 'Turquia',
  'United States': 'Estados Unidos',
  Uruguay: 'Uruguai',
  Uzbekistan: 'Uzbequistão',
}

export function getTeamName(teamName: string): string {
  return TEAM_NAMES_PT[teamName] ?? teamName
}
